services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog_app
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local