services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog_app
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    command: ["redis-server",
              "--requirepass", "radmin",
              "--appendonly", "yes"]
    networks:
      - dev_back

  elasticsearch:
    image: elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - http.port=9200
      - http.cors.allow-origin=http://0.0.0.0:1358
      - http.cors.enabled=true
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - network.publish_host=localhost
    ports:
      - "9200:9200"
    volumes:
      - esdata:/var/lib/elasticsearch/data
    networks:
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

  dejavu:
    image: appbaseio/dejavu:latest
    ports:
      - "1358:1358"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:radmin
    ports:
      - "8081:8081"
    networks:
      - "dev_back"

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  esdata:
    driver: local

networks:
  esnet:
  dev_back: