services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog_app
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    command: ["redis-server",
              "--requirepass", "radmin",
              "--appendonly", "yes"]

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local