"""import_article_id_field_to_article_table

Revision ID: a3c98efde516
Revises: f01783929a8a
Create Date: 2024-09-13 01:12:37.681595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3c98efde516"
down_revision: Union[str, None] = "f01783929a8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("import_article_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "import_article_id")
    # ### end Alembic commands ###
